### ISSUE TITLE
Default arguments

### ISSUE THREAD

**Issue by jjl** [OvermindDL1/protocol_ex#10]
It would be nice to be able to define a function in a protocol that uses optional arguments with `\\`

**Comment by OvermindDL1** [comment]
I've thought of that but the issue is such way to consider things.  First, should defaults just be allowed on the protocol?  Or second, should I allow implementations to have their own default args, which may have some corner cases that I considered a while back but can't remember currently.  Is the first sufficient?

**Comment by jjl** [comment]
I was considering only protocols having default args here. I imagine it would work like this:

```elixir
defprotocolEx FooBar, %Foo{}, for: Bar do
  def bar(x, y \\ nil)
end
```

Would be the equivalent of this:

```elixir
defprotocolEx FooBar, %Foo{}, for: Bar do
  def bar(x), do: bar(x,nil)
  def bar(x, y)
end
```

**Comment by OvermindDL1** [comment]
Added it in, and I allowed protocols to override the defaults as well if so wanted.  :-)
